language: node_js

node_js:
  - 14

cache:
  directories:
    - "node_modules"

script:
  - yarn lint
  - yarn test
  # - yarn build
  # - yarn export

# deploy:
#   provider: s3
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
#   bucket: my-trips
#   region: sa-east-1
#   skip_cleanup: true
#   local_dir: out
#   on:
#     branch: main
