language: node_js
node_js:
  - 14

cache:
  directories:
    - "node_modules"

script:
  - yarn test
  - yarn build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: my-trips
  skip_cleanup: true
  local_dir: .next
  on:
    branch: main
